SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/player_signin/'
SOCIAL_AUTH_LOGIN_URL = '/'

GOOGLE_API_KEY = 'AIzaSyBfV4zrik3QLmHD-LxSEt6AMUaj4xAteek'

SOCIAL_AUTH_TWITTER_KEY = 'TGyJSOCXh4Z0pDVpf6fNzgeff'
SOCIAL_AUTH_TWITTER_SECRET = 'LWoInoEzb4MoQvvarJzvCcnM7FCpD5Qk3My70t7MQQMpitrEGf'
