# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.FloatField()),
                ('address', models.CharField(max_length=500)),
                ('availability_days', models.CharField(max_length=500)),
                ('availability_times', models.CharField(max_length=500)),
                ('looking_for', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('additional_info', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, null=True)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
