# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('skill_level', models.DecimalField(decimal_places=2, max_digits=2)),
                ('address', models.CharField(max_length=500)),
                ('availability_days', models.CharField(max_length=500)),
                ('availability_times', models.CharField(max_length=500)),
                ('looking_for', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
