# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20170710_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_attributes',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='player_attributes',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='player_attributes',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
