# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20170710_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_attributes',
            name='lattitude',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player_attributes',
            name='longitude',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
