# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20170718_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_attributes',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
