# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20170718_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_attributes',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='player_attributes',
            name='longitude',
        ),
    ]
