# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20170719_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_attributes',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='player_attributes',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
