# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_auto_20170725_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_attributes',
            name='username',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
