# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20170725_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_attributes',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
